dist: xenial
language: python
python:
- '3.7'
addons:
  apt:
    update: true
    packages:
    - jq
    - awscli
before_install:
- openssl aes-256-cbc -K $encrypted_821f4b5ca00e_key -iv $encrypted_821f4b5ca00e_iv
  -in .env.tar.enc -out .env.tar -d
- tar xvf .env.tar
install:
- pip install "terraform-ci~=1.2"
- install-terraform --terraform-version 0.12.24
script:
- make bootstrap test
- terraform-ci --modules-path dev/foo_service --module-name dev:foo_service plan
- terraform-ci --modules-path staging/foo_service --module-name staging:foo_service
  plan
- terraform-ci --modules-path prod/foo_service --module-name prod:foo_service plan
deploy:
- provider: script
  skip_cleanup: true
  script: terraform-ci --modules-path dev/foo_service apply
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: terraform-ci --modules-path staging/foo_service apply
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: terraform-ci --modules-path prod/foo_service apply
  on:
    branch: master
